/**
 * The PostgREST child process.
 *
 * PostgREST is the real thing, not a stand-in: the same binary a hosted project
 * runs, reading the same migrations, enforcing the same RLS. It is the reason
 * this harness is worth having — every `select`, every `insert` and every
 * `rpc()` the app makes is answered by it, as `anon` or `authenticated`,
 * against real policies.
 */

import { spawn, type ChildProcess } from 'node:child_process';
import fs from 'node:fs/promises';
import net from 'node:net';

import {
  JWT_SECRET,
  POSTGREST_CONFIG_PATH,
  POSTGREST_HOST,
  POSTGREST_PORT,
  postgresUri,
  STATE_DIR,
} from './config.mjs';

export interface PostgrestHandle {
  process: ChildProcess;
  stop: () => Promise<void>;
}

/** PostgREST's config file format is `key = "value"`, one per line. */
function configFile(): string {
  return [
    '# Generated by scripts/dev-stack/start.mts. Do not edit; it is overwritten.',
    `db-uri = "${postgresUri()}"`,
    'db-schemas = "public"',
    'db-anon-role = "anon"',
    `jwt-secret = "${JWT_SECRET}"`,
    `server-host = "${POSTGREST_HOST}"`,
    `server-port = ${POSTGREST_PORT}`,
    'db-pool = 10',
    // Match Supabase's default ceiling so a missing `.limit()` behaves the same
    // here as it would in a real project.
    'db-max-rows = 1000',
    'log-level = "error"',
    '',
  ].join('\n');
}

export async function startPostgrest(): Promise<PostgrestHandle> {
  await fs.mkdir(STATE_DIR, { recursive: true });
  await fs.writeFile(POSTGREST_CONFIG_PATH, configFile(), { mode: 0o600 });

  const child = spawn('postgrest', [POSTGREST_CONFIG_PATH], {
    stdio: ['ignore', 'pipe', 'pipe'],
    // Same process group as the stack, so a stray Ctrl-C reaches it too. It is
    // still killed explicitly in `stop()` — belt and braces, because an orphan
    // PostgREST holds port 54322 and breaks the next run.
    detached: false,
  });

  const prefix = (line: string) => `[postgrest] ${line}`;
  child.stdout?.on('data', (chunk: Buffer) => {
    process.stdout.write(prefix(chunk.toString()));
  });
  child.stderr?.on('data', (chunk: Buffer) => {
    process.stderr.write(prefix(chunk.toString()));
  });

  let stopped = false;
  const stop = async (): Promise<void> => {
    if (stopped) return;
    stopped = true;
    if (child.exitCode !== null || child.signalCode !== null) return;

    await new Promise<void>((resolve) => {
      const done = () => resolve();
      child.once('exit', done);
      child.kill('SIGTERM');
      // If it will not go quietly within a second, it goes anyway.
      setTimeout(() => {
        if (child.exitCode === null && child.signalCode === null) {
          child.kill('SIGKILL');
        }
      }, 1000).unref();
    });
  };

  child.on('exit', (code, signal) => {
    if (!stopped) {
      console.error(
        `[dev-stack] postgrest exited unexpectedly (code ${String(code)}, signal ${String(signal)}).`,
      );
    }
  });

  await waitForPort(POSTGREST_HOST, POSTGREST_PORT, 20_000, child);
  return { process: child, stop };
}

/** Poll a TCP port until something is listening, or give up. */
export async function waitForPort(
  host: string,
  port: number,
  timeoutMs: number,
  child?: ChildProcess,
): Promise<void> {
  const deadline = Date.now() + timeoutMs;

  for (;;) {
    if (child && (child.exitCode !== null || child.signalCode !== null)) {
      throw new Error(
        `postgrest exited before it began listening on ${host}:${port}. ` +
          'Its output is above; the usual cause is that the database does not exist yet.',
      );
    }

    const open = await new Promise<boolean>((resolve) => {
      const socket = net.connect({ host, port });
      const settle = (value: boolean) => {
        socket.destroy();
        resolve(value);
      };
      socket.once('connect', () => settle(true));
      socket.once('error', () => settle(false));
      socket.setTimeout(500, () => settle(false));
    });

    if (open) return;
    if (Date.now() > deadline) {
      throw new Error(`nothing came up on ${host}:${port} within ${timeoutMs}ms`);
    }
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
}
